stages:
  - validate
  - build


lint:
  stage: validate
  script:
    - make lint

build_package:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - make package.ci
    - make semantic-release
